### ISSUE TITLE
The page of pdfjs is error

### ISSUE THREAD

**Issue by Thj007** [yurydelendik/pdfjs-react#1]
i'm make a project about the pdf preview, but i found some pdf page font is error code.
such as : i want the pdf can show like this:
![right](https://user-images.githubusercontent.com/30485600/35478433-6216d6aa-0418-11e8-84a4-29a960924fd0.png)
but i get it like this:
![error](https://user-images.githubusercontent.com/30485600/35478435-6f899cdc-0418-11e8-89ba-4fe84b47189a.png)
Can you help me ?

**Comment by yurydelendik** [comment]
Probably cmap information/path is not provided. See https://github.com/mozilla/pdf.js/blob/628e70fbb5dea3b9066aa5c34cca70aaafef8db2/src/display/api.js#L142. Closing as answered.
